### ISSUE TITLE
Suggestion - add create playlist feature

### ISSUE THREAD

**Issue by vicone666** [smedic/Android-YouTube-Background-Player#1]
The app is awesome, if you could implement user making playlists, saving and playing them that would  do wonders for this already good product.

**Comment by smedic** [comment]
Hello.

I agree, that will be the next feature.
I have uploaded apk to my 1st release here, so you can try the app.

**Comment by vicone666** [comment]
I tried it, i like it very much, keep up the good work man.

**Comment by smedic** [comment]
Thank you. 
I will continue to improve the app :)
