### ISSUE TITLE
Request: timeline

### ISSUE THREAD

**Issue by JonnyTech** [smedic/Android-YouTube-Background-Player#14]
Is it possible to have a timeline of the current track and have the ability to jump to times like a scrollbar?

**Comment by smedic** [comment]
I have seen that a few times, but it is always related to downloading and it's progress bar. Do you know any music app that has that feature? Just to check how they handle seek action. Is is not so convenient to jump by touching...

**Comment by JonnyTech** [comment]
[NewPipe](https://github.com/TeamNewPipe/NewPipe) has this feature, it has a seekbar in the [VideoPlayer](https://github.com/TeamNewPipe/NewPipe/tree/master/app/src/main/java/org/schabi/newpipe/player) code.

**Comment by smedic** [comment]
It is a progress bar. You cannot actually jump between times in app. Am I right?

**Comment by JonnyTech** [comment]
Yes, jump forward and back in a playing track.

**Comment by smedic** [comment]
Okay, I see. You must press forward and back. But then you cannot listen to a playlist and listen one by one song. I can add fast forward button, beside previous/next. Is that going to be okay?

**Comment by JonnyTech** [comment]
Not sure, will wait to see what you decide to implement - thanks.
