### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by loucass003** [smedic/Android-YouTube-Background-Player#15]
Hi i have tested your app.
Good project ;)
But you can add some feature to make it better.

 - add a timeline to skip part of musics
- add headset controls (1 press play/pause - 2 press next track - 3 press prev track)
- playlist view does not working i think 

sorry for my English (Hi from france ;) )

**Comment by smedic** [comment]
Bonjour! 

I am glad you like it. 

I don't have time to work on this, but you are free to add whatever you like and make a pull request. 
If I find some time, I will try to implement your ideas :)

Greetings for France from Serbia!
