### ISSUE TITLE
Export APK 

### ISSUE THREAD

**Issue by VAdaihiep** [smedic/Android-YouTube-Background-Player#19]
I know you can not publish this app to Google Play but could you export an APK and upload here?
Thanks!

**Comment by VAdaihiep** [comment]
I found APK in https://github.com/smedic/Android-YouTube-Background-Player/releases 
Hope you can add download url in README.md.

**Comment by smedic** [comment]
Hi! Thanks for suggestion. 
I added instructions where to find releases and download APK.

If you have any ideas and you are willing to contribute, please do so, I will highly appreciate that.

Best regards!
