### ISSUE TITLE
Suggestion - implement custom media player buttons

### ISSUE THREAD

**Issue by oantajames** [smedic/Android-YouTube-Background-Player#2]
The app is great! But besides the media controlers that are accessible on the notifications drawer, it will be nice if you can add some controllers for the media player inside the app (ex. play pause skip shuffle seek bar so you can skip to certain seconds from the song etc.)
Nice work! Well done :+1:  :100:

**Comment by smedic** [comment]
Thank you for your support :) 
I will try to implement that soon :)

**Comment by NamPNQ** [comment]
Great if have seek feature
