### ISSUE TITLE
Wrong version number in latest release

### ISSUE THREAD

**Issue by IzzySoft** [smedic/Android-YouTube-Background-Player#8]
...and probably in all after the initial release. I've just checked 1.05, and it shows:

```
package: name='com.smedic.tubtub' versionCode='1' versionName='1.0'
```

which should rather read something like

```
package: name='com.smedic.tubtub' versionCode='6' versionName='1.05'
```

When fixing it, please take care to always update both, versionName _and_ versionCode. Gives some trouble on updates otherwise :)

Thanks in advance!

**Comment by smedic** [comment]
You are totally right. I forgot to update this. 
Thanks! 

Feel free to make pull requests and add features.

**Comment by IzzySoft** [comment]
Thanks to you! I assume versionCode and versionName will be fixed with the next release – or do you plan to replace the file from the current latest release (1.0.5)?

I'm not an Android dev, so sorry if I cannot follow your invitation concerning pull requests. I'm just running a little [F-Droid compatible repository](https://android.izzysoft.de/repo) with apps from Github not available at F-Droid itself – so people without access to Google Play Store have something to feed their devices with :)

**Comment by smedic** [comment]
Is it okay for you that I do the following for next release:
versionCode='7' versionName='1.06' ? I can replace current file if you like.

**Comment by IzzySoft** [comment]
As the recent release has '1' and '1.0', that's fine. If you replace the current file using '6' and '1.05', the repo would reflect the correct version, so I (and probably the users as well) would welcome that :)

**Comment by smedic** [comment]
File is replaced. Now in the latest release, you have apk with 6, 1.05.

**Comment by smedic** [comment]
I am glad if anyone uses this app :)

**Comment by IzzySoft** [comment]
> File is replaced. Now in the latest release, you have apk with 6, 1.05.

Yupp, I've noticed – my auto-updater had pulled and announced it today – you can see it if you filter the list for "updated since 1 day" :)

> I am glad if anyone uses this app :)

Sure! That's one part of what my repo is for, to make good apps known :)

Thanks a lot again!
